# GitHub Actions Workflow to Keep n8n Active
# Place this file in: .github/workflows/n8n-keepalive.yml

name: n8n Keep-Alive

on:
  schedule:
    # Keep alive during working hours (UTC)
    # 04:00-12:00 UTC = 09:30-17:30 IST (Indian working hours)
    - cron: '*/15 4-12 * * 1-5'  # Every 15 minutes, Mon-Fri, working hours
    # Light pings during weekend/off-hours
    - cron: '0 */2 * * *'        # Every 2 hours, all days

  workflow_dispatch: # Allow manual triggering

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n Instance
        run: |
          echo "ðŸš€ Pinging n8n instance..."

          # Check if it's working hours (4-12 UTC)
          current_hour=$(date -u +%H)
          current_day=$(date -u +%u)  # 1=Monday, 7=Sunday

          if [[ $current_hour -ge 4 && $current_hour -le 12 && $current_day -le 5 ]]; then
            echo "ðŸ“… Working hours - performing detailed health check"

            # Detailed health check during working hours
            response=$(curl -s -o /dev/null -w "%{http_code}" https://n8n.assistt.in/)

            if [[ $response == "200" ]]; then
              echo "âœ… n8n is healthy (HTTP $response)"
            else
              echo "âš ï¸  n8n returned HTTP $response"
            fi

            # Additional ping to ensure it stays warm
            curl -s https://n8n.assistt.in/ > /dev/null

          else
            echo "ðŸŒ™ Off-hours - light ping only"
            curl -s -I https://n8n.assistt.in/ > /dev/null
          fi

          echo "âœ… Keep-alive ping completed"

      - name: Log Usage Stats
        run: |
          echo "ðŸ“Š Estimated daily usage:"
          # Working hours: 15min intervals Ã— 9 hours Ã— 5 days = 180 pings/week
          # Off-hours: 2hr intervals Ã— remaining time = ~84 pings/week
          # Total: ~264 pings/week = ~1,126 pings/month (well within 2M limit)
          echo "- Working hours pings: ~36/day (Mon-Fri)"
          echo "- Off-hours pings: ~12/day"
          echo "- Total estimated: ~1,200 requests/month (0.06% of free limit)"
          echo "- Container runtime: ~2-3 hours/day (well within free limit)"