name: N8N Keep Alive

on:
  schedule:
    # Every 15 minutes from 12 PM to 5 PM IST (Mon-Sat)
    - cron: '*/15 6-11 * * 1-6'
    # Every 15 minutes from 11 AM to 1 AM IST (Sun)
    - cron: '*/15 5-19 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping n8n instance
        run: |
          echo "Pinging n8n to prevent cold start..."

          # Get current time for logging
          echo "Current time: $(date)"

          # Ping the n8n instance
          response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 https://n8n.assistt.in || echo "000")

          if [ "$response" = "200" ] || [ "$response" = "401" ] || [ "$response" = "302" ]; then
            echo "✅ n8n is responding (HTTP $response)"
          elif [ "$response" = "000" ]; then
            echo "⚠️  n8n might be cold starting (no response) - this is normal"
          else
            echo "⚠️  n8n returned HTTP $response - might be starting up"
          fi

          # Wait a bit and try again if first attempt failed
          if [ "$response" = "000" ]; then
            echo "Waiting 30 seconds and trying again..."
            sleep 30
            response2=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 https://n8n.assistt.in || echo "000")
            echo "Second attempt: HTTP $response2"
          fi

          echo "Keep-alive ping completed"

      - name: Log status
        run: |
          echo "Job completed at $(date)"
          echo "Next scheduled run will occur based on cron schedule"
